apiVersion: v1
kind: Pod
metadata:
  name: kucc1
spec:
  containers:
  - name: nginx1
    image: nginx:1.14.2

  - name: redis1
    image: redis:latest

  - name: memcached1
    image: memcached:latest

  - name: consul1
    image: hashicorp/consul:latest
